#!/usr/bin/env bash
set -e
script_name="$(basename "${BASH_SOURCE}")"
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

while [[ "$#" > 0 ]]; do
	case "$1" in
		-g|--gpg|gpg=) gpgkey="$2"; shift ;;
		-e|--export-public-key|--export-public-key=) exportkey="1"; shift ;;
		*) shift ;;
	esac
done

archives=$(ls conf/apt-*-release.conf | sed -r 's/conf\/apt-(.*)-release\.conf/\1/')
[ -z "${archives}" ] && echo "Command must be executed from within an APT repository root directory." && exit 1

for archive in $archives; do
	echo "Generating 'Release' file for '${archive}'."

	apt-ftparchive -c "conf/apt-${archive}-release.conf" release \
		"dists/${archive}" > "dists/${archive}/Release"

	[ -f "dists/${archive}/Release.gpg" ] && rm "dists/${archive}/Release.gpg"

	[ -n "${gpgkey}" ] && echo "Signing Release file" && (gpg --use-agent -u"${gpgkey}" \
		--output "dists/${archive}/Release.gpg" -ba "dists/${archive}/Release" || exit 1)
done

[ -n "${gpgkey}" ] && [ -n "${exportkey}" ] && gpg --export -a "${gpgkey}" > pubkey.asc 

echo "APT repository update completed."
exit 0
