#!/usr/bin/env bash
set -e
script_name="$(basename "$BASH_SOURCE")"
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function usage() {
cat <<-EOF
raptr is a simple APT Repository builder and updater.  It relies on apt-ftparchive and GPG to do the heavy lifting.

Example usage:

$script_name new --archives "production staging testing" --sections "public private"
$script_name add --name "my-package-name" --dir "/location/to/some/package-dir" # can add deb and dsc-related stuff
$script_name update gpg="mykey@domain.com" # gpg key is optional
EOF
}

case "$1" in
  new|add|update) "$script_dir/$script_name-$1" "${@:2}" ;;
  *) usage ;; 
esac

exit 0
