#!/usr/bin/env bash
set -e
script_name="$(basename "${BASH_SOURCE}")"
script_dir="$( cd "$( dirname $(readlink -f "${BASH_SOURCE[0]}" ))" && pwd )"

function usage() {
cat <<-EOF
raptr is a simple APT repository builder and updater.  It relies on apt-ftparchive, dpkg-scan(packages|sources) and GPG to do the heavy lifting.

Example usage:

################################################################

Creating a new APT repository:

${script_name} init \\
  --archives "production staging testing" \\
  --sections "public private" \\
  --cpus "amd64 i386 source"

################################################################

Adding various kinds of packages to an existing repository:

${script_name} add \\
  --target "*/public"
  --package "/path/to/package/*"

${script_name} add \\
  --target "*/public"
  --package my-package.deb

${script_name} add \\
  --target "production/public"
  --package my-package.dsc

${script_name} add \\
  --target "testing/private"
  --package my-package.deb

################################################################

Updating the repository indices such that it can be published:

${script_name} update \\
  --gpg="mykey@domain.com"
  --export-public-key

################################################################

EOF
}

case "$1" in
  init|add|update) "${script_dir}/${script_name}-$1" "${@:2}" ;;
  *) usage ;; 
esac

exit 0
